/*
 * Generated by TI MCU NNC 2.0.0
 * cross-compiler: /home/tushxr16/bin/ti-cgt-c2000_22.6.1.LTS/bin/cl2000
 * cross-compiler-opts: --abi=eabi -O3 --opt_for_speed=5 --c99 -v28 -ml -mt --gen_func_subsections --float_support=fpu32 -I/home/tushxr16/bin/ti-cgt-c2000_22.6.1.LTS/include -I/home/tushxr16/bin/C2000Ware_6_00_00_00/driverlib/f28004x/driverlib -I/home/tushxr16/bin/C2000Ware_6_00_00_00/device_support/f28004x/common/include -I. -Iartifacts --obj_directory=.
 * input model file: /home/tushxr16/tiny-ml/tinyml-modelmaker/data/projects/dc_arc_fault_example_dsk/run/running_model_on_device_without_npu/training/quantization/model.onnx
 * module name: default
 */

#ifndef TVMGEN_DEFAULT_H_
#define TVMGEN_DEFAULT_H_
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Symbol defined when running model on the host processor */
#define TVMGEN_DEFAULT_TI_NPU_SOFT
#ifdef TVMGEN_DEFAULT_TI_NPU
	#error Conflicting definition for where model should run.
#endif

/* The generated model library expects the following inputs/outputs:
 * Inputs:
 *    Tensor[(1, 1, 256, 1), int8]
 * Outputs:
 *    Tensor[(1, 2), int8]
 */

/* Input feature normalization parameters:
 *   input_int = clip(((int32_t)((input_float + bias) * scale)) >> shift, min, max)
 *   where (min, max) = (-128, 127) if int8 type, (0, 255) if uint8 type
 */
#define TVMGEN_DEFAULT_BIAS_LEN 1
#define TVMGEN_DEFAULT_SCALE_LEN 1
#define TVMGEN_DEFAULT_SHIFT_LEN 1
extern const float tvmgen_default_bias_data[] __attribute__((weak)) = {0.5};
extern const int32_t tvmgen_default_scale_data[] __attribute__((weak)) = {128};
extern const int32_t tvmgen_default_shift_data[] __attribute__((weak)) = {7};


/*!
 * \brief Input tensor pointers for TVM module "default" 
 */
struct tvmgen_default_inputs {
  void* onnx__Add_0;
};

/*!
 * \brief Output tensor pointers for TVM module "default" 
 */
struct tvmgen_default_outputs {
  void* output;
};

/*!
 * \brief entrypoint function for TVM module "default"
 * \param inputs Input tensors for the module 
 * \param outputs Output tensors for the module 
 */
int32_t tvmgen_default_run(
  struct tvmgen_default_inputs* inputs,
  struct tvmgen_default_outputs* outputs
);

#ifdef __cplusplus
}
#endif

#endif // TVMGEN_DEFAULT_H_
