
common:
    target_module: 'timeseries'
    task_type: 'arc_fault'
    target_device: 'F28P55'
    run_name: '{date-time}/{model_name}'
#    run_name: '20240529-150933'
dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_name: arc_fault_example_dsk
#    input_data_path: '/home/a0484689/PycharmProjects/tinyml_docker_images/arc_fault_classification_dsk.zip'

data_processing: # One or more can be cascaded in the list
    # transform: [ DownSample, SimpleWindow ]
    # transform: 'DownSample SimpleWindow'
    variables: 1
    transform: [ ]
    org_sr: 1
    new_sr: 1
    stride_window: 1
    unit: 'time' # time or samples

feature_extraction:
    feature_extraction_name: ArcFault_1024Input_FFT
    feature_size_per_frame: 512
    num_frame_concat: 8
    min_fft_bin: 1
    fft_bin_size: 1

training:
    # enable/disable training
    enable: True #False
    # F28x generic timeseries model names: TimeSeries_Generic_AF_3k_t, TimeSeries_Generic_AF_7k_t
    # GUI only model names: ArcFault_model_200_t, ArcFault_model_300_t, ArcFault_model_700_t
    model_name: 'ArcFault_model_200_t'
#    model_spec: '../tinyml-mlbackend/proprietary_models/cnn_af_3l.py'
    model_config: ''
    dataset_loader: ArcFaultDataset
    batch_size: 64
    training_epochs: 10
    num_gpus: 0
#    run_quant_train_only: True
#    training_path_quantization:
testing:
    test_quant_model: True
#    test_data: ./data/projects/arc_fault_example_dsk/dataset/classes


compilation:
    # enable/disable compilation
    enable: True #False
#    model_path: Onnx/tflite Model Path fro BYOM for compilation only
    # No preset is required for F28P55
#    preset_name: default_preset
#    preset_name: best_performance_preset
