
common:
    target_module: 'timeseries'
    task_type: 'arc_fault'
    target_device: 'F28P55'
    run_name: '{date-time}/{model_name}'
dataset:
    # enable/disable dataset loading
    enable: True
    dataset_name: arc_fault_example_dsi
#    split_names: [training, validation]

data_processing: # One or more can be cascaded in the list
    transforms: [ Downsample, SimpleWindow ]
    # transforms: 'DownSample SimpleWindow'
    # org_sr: 313000
    # new_sr: 3009
    # stride_window: 0.001
    # sequence_window: 0.25
    org_sr: 313000
    new_sr: 3200
    stride_window: 0.001
    sequence_window: 0.16
    unit: 'time' # time or samples
    variables: 1

feature_extraction:
    transform: None

training:
    # enable/disable training
    enable: True #False
    # F28x generic timeseries model names: TimeSeries_Generic_3k_t, TimeSeries_Generic_7k_t
    # GUI only model names: ArcFault_model_200_t, ArcFault_model_300_t, ArcFault_model_700_t
    model_name: 'TimeSeries_Generic_7k_t'
    # model_spec: '../tinyml-mlbackend/proprietary_models/cnn_af_3l.py'
    model_config: ''
    batch_size: 64
    training_epochs: 5 #10
    num_gpus: 1

compilation:
    # enable/disable compilation
    enable: True #False
#    compile_preset_name: 'default_preset'
