
common:
    target_module: 'timeseries'
    task_type: 'arc_fault'
    target_device: 'F28P55'
    run_name: '{date-time}/{model_name}'
#    run_name: '20240710-191631'
dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_name: arc_fault_example_dsk
#    input_data_path: '/home/a0484689/PycharmProjects/tinyml_docker_images/arc_fault_classification_dsk.zip'
#    split_type: within_files

data_processing_feature_extraction:
    # One or more can be cascaded in the list
    # transforms: 'DownSample SimpleWindow'
    data_proc_transforms: []
    # Downsample
    #sampling_rate: 313000
    #new_sr: 3130
    # SimpleWindow
    #frame_size: 256
    #stride_size: 0.01

    feature_extraction_name: FFT1024Input_256Feature_1Frame_Full_Bandwidth
#   feature_extraction_name: FFT1024Input_256Feature_1Frame_Half_Bandwidth
#   feature_extraction_name: FFT1024Input_64Feature_4Frame_Half_Bandwidth
#   feature_extraction_name: FFT1024Input_32Feature_8Frame_Quarter_Bandwidth
#   feature_extraction_name: Custom_ArcFault
#   feat_ext_transform: []
#   frame_size: 1024
#   feature_size_per_frame: 128
#   num_frame_concat: 1
#   min_bin: 4
#   analysis_bandwidth: 1
#   frame_skip: 1
#   store_feat_ext_data: False
#   nn_for_feature_extraction: True
    variables: 1

training:
    # enable/disable training
    enable: True #False
    # F28x generic timeseries model names: TimeSeries_Generic_1k_t, TimeSeries_Generic_4k_t, TimeSeries_Generic_6k_t, TimeSeries_Generic_13k_t
    # GUI only model names: ArcFault_model_200_t, ArcFault_model_300_t, ArcFault_model_700_t, ArcFault_model_1400_t
    model_name: 'TimeSeries_Generic_1k_t'
#    with_input_batchnorm: False
#    model_spec: '../tinyml-mlbackend/proprietary_models/cnn_af_3l.py'
    model_config: ''
    batch_size: 32
    training_epochs: 10
    num_gpus: 0
#    quantization_method: 'QAT'  # QAT/PTQ
#    quantization_weight_bitwidth: 2
#    quantization_activation_bitwidth: 8
#    augment_config: 'misc/augmenter_config.yaml'
#    quantization: 2

testing:
    enable: True
    skip_train: False  # True if only the model needs to be tested (BYOM for testing). model_path below needs to be given
#    model_path: Onnx/tflite Model Path for BYOM for compilation only
#    test_data: ./data/projects/arc_fault_example_dsk/dataset/classes  #  if dataset is being provided here then- dataset-> enable: False


compilation:
    # enable/disable compilation
    enable: True #False
    # No preset is required for devices other than F28P55
    #    preset_name: default_preset/ forced_soft_npu_preset
#    compile_preset_name: forced_soft_npu_preset
