
common:
    target_module: 'timeseries'
    task_type: 'motor_fault'
    target_device: 'F28P55'
    run_name: '{date-time}/{model_name}'
dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_name: motor_fault_example_dsk

data_processing: # One or more can be cascaded in the list
    transform: [ ]
    sampling_rate: 1
    new_sr: 1
    stride_window: 1
    sequence_window: 256
    variables: 3
    unit: 'samples' # time or samples

feature_extraction:
    feature_extraction_name: MotorFault_256Input_FFTBIN_16Feature_8Frame_3InputChannel_removeDC_2D1

training:
    # enable/disable training
    enable: True #False
    dataset_loader: MotorFaultDataset
    # F28x generic timeseries model names: TimeSeries_Generic_3k_t, TimeSeries_Generic_7k_t
    # GUI only model names: MotorFault_model_1_t, MotorFault_model_2_t, MotorFault_model_3_t
    model_name: 'MotorFault_model_1_t'
#    model_spec: '../tinyml-mlbackend/proprietary_models/cnn_mf_1l.py'
    model_config: ''
    batch_size: 256
    training_epochs: 15
    num_gpus: 0  # 1
    learning_rate: 0.04

testing:
    enable: True

compilation:
    # enable/disable compilation
    enable: True #False
    # No preset is required for devices other than F28P55
    compile_preset_name: forced_soft_npu_preset
