[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tinyml_modelmaker"
version = "1.0.0"
description = "Tiny ML ModelMaker"
authors = [
    { name = "Adithya Thonse", email = "thonse@ti.com" }
]
license = { text = "BSD 3-Clause" }
readme = "README.md"
requires-python = "==3.10.*"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.10"
]
dependencies = [
    "defusedxml==0.7.1",
    "numpy==1.26.4",
    "pandas==2.2.2",
    "pathlib2==2.3.7.post1",
    "PyYAML==6.0.2",
    "tqdm==4.66.5",
    "requests==2.32.3",
#    "tinyml_tinyverse @ git+ssh://git@bitbucket.itg.ti.com/tinyml-algo/tinyml-tinyverse.git",
    "tinyml_tinyverse @ git+https://github.com/TexasInstruments/tinyml-tensorlab.git@main#subdirectory=tinyml-tinyverse",
    # TinyVerse
    "onnx==1.16.1",
    "onnxruntime==1.19.0",
    "protobuf==5.27.3",
    "pathlib2==2.3.7.post1",
    "scipy==1.13.1",
    "tabulate==0.9.0",
    "torcheval==0.0.7",
    "torchinfo==1.8.0",
    "cryptography==43.0.1",
    "matplotlib==3.9.2",
    "scikit-learn==1.5.2",
    "torch==2.3.0",
    "pycocotools",
    "opencv-python",
#    "tinyml_torchmodelopt @ git+ssh://git@bitbucket.itg.ti.com/tinyml-algo/tinyml-modeloptimization.git@main#subdirectory=torchmodelopt",
    "tinyml_torchmodelopt @ git+https://github.com/TexasInstruments/tinyml-tensorlab.git@main#subdirectory=tinyml-modeloptimization/torchmodelopt",
    "ti_mcu_nnc @ https://software-dl.ti.com/mctools/esd/tvm/mcu/ti_mcu_nnc-1.3.0-cp310-cp310-linux_x86_64.whl ; platform_system == 'Linux'",
    "ti_mcu_nnc @ https://software-dl.ti.com/mctools/esd/tvm/mcu/ti_mcu_nnc-1.3.0-cp310-cp310-win_amd64.whl ; platform_system == 'Windows'",
    # TorchmodelOpt
    "Cython==3.0.11",
    "protobuf==5.27.3",
    "pillow==10.4.0",
    "onnxsim==0.4.36",
    "onnxsim==0.4.36",
    "onnxoptimizer==0.3.13",
    "progressbar==2.5",
    "rich==13.7.1",
#    "edgeai_torchmodelopt @ git+https://github.com/TexasInstruments/edgeai-modeloptimization.git@r10.0#subdirectory=torchmodelopt",

]

[project.urls]
"Homepage" = "https://github.com/TexasInstruments/tinyml-tensorlab/tree/main/tinyml-modelmaker"

[tool.setuptools]
include-package-data = true


[tool.setuptools.packages.find]
include = ["tinyml_modelmaker*"]
exclude = ["tests*"]

[tool.setuptools.dynamic]
version = {attr = "tinyml_modelmaker.__version__"}
