common:
  target_module: audio
  task_type: audio_classification
  target_device: MSPM0G5187
dataset:
  dataset_name: google_speech_commands_12class
  input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/01_04_00/datasets/google_speech_commands_12class.zip
data_processing_feature_extraction:
  feature_extraction_name: GoogleSpeechCommands_MFCC_Default
training:
  model_name: DSCNN_NPU
  batch_size: 64
  training_epochs: 20
  num_gpus: 0
  quantization: 2
  learning_rate: 0.1
  weight_decay: 1e-5
testing: {}
compilation: {}