
common:
    target_module: 'timeseries'
    task_type: 'arc_fault'
    target_device: 'F28P55'
    run_name: '{date-time}/{model_name}'
#    run_name: '20240710-191631'
dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_name: arc_fault_example_dsk
#    input_data_path: '/home/a0484689/PycharmProjects/tinyml_docker_images/arc_fault_classification_dsk.zip'

data_processing: # One or more can be cascaded in the list
    # transform: [ DownSample, SimpleWindow ]
    # transform: 'DownSample SimpleWindow'
    variables: 1
    transform: [ ]
    org_sr: 1
    new_sr: 1
    stride_window: 1
    unit: 'time' # time or samples

feature_extraction:
    feature_extraction_name: FFT1024Input_256Feature_1Frame_Full_Bandwidth
#    feature_size_per_frame: 512
#    num_frame_concat: 8
#    min_fft_bin: 1
#    fft_bin_size: 1
#    frame_skip: 3

training:
    # enable/disable training
    enable: True #False
    # F28x generic timeseries model names: TimeSeries_Generic_3k_t, TimeSeries_Generic_7k_t
    # GUI only model names: ArcFault_model_200_t, ArcFault_model_300_t, ArcFault_model_700_t
    model_name: 'ArcFault_model_200_t'
#    model_spec: '../tinyml-mlbackend/proprietary_models/cnn_af_3l.py'
    model_config: ''
    dataset_loader: ArcFaultDataset
    batch_size: 64
    training_epochs: 10
    num_gpus: 0

testing:
    enable: True
    skip_train: False  # True if only the model needs to be tested. model_path below needs to be given
#    model_path: Onnx/tflite Model Path for BYOM for compilation only
#    test_data: ./data/projects/arc_fault_example_dsk/dataset/classes  #  if dataset is being provided here then- dataset-> enable: False


compilation:
    # enable/disable compilation
    enable: True #False
    # No preset is required for devices other than F28P55
    #    preset_name: default_preset/ forced_soft_npu_preset
#    compile_preset_name: forced_soft_npu_preset
