
common:
    target_module: 'timeseries'
    task_type: 'generic_timeseries_classification'
    target_device: 'F28P55'
    run_name: '{date-time}/{model_name}'
dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_name: hello_world_example_dsg
#    input_data_path: http://software-dl.ti.com/C2000/esd/mcu_ai/01_00_00/datasets/hello_world_dsg.zip
#    split_type: within_files
#    gof_test: True


data_processing_feature_extraction:
    feature_extraction_name: Generic_1024Input_FFTBIN_64Feature_8Frame
#    feature_extraction_name: Generic_512Input_FFTBIN_32Feature_8Frame
#    feature_extraction_name: Generic_256Input_FFTBIN_16Feature_8Frame
#    feature_extraction_name: Generic_1024Input_FFT_512Feature_1Frame
#    feature_extraction_name: Generic_512Input_FFT_256Feature_1Frame
#    feature_extraction_name: Generic_256Input_FFT_128Feature_1Frame
#    feature_extraction_name: Generic_512Input_RAW_512Feature_1Frame
#    feature_extraction_name: Generic_256Input_RAW_256Feature_1Frame
#    feature_extraction_name: Generic_128Input_RAW_128Feature_1Frame

    variables: 1
#    frame_size: 1024
#    feature_size_per_frame: 64
#    num_frame_concat: 4
#    transform: ['FFT_FE', 'FFT_POS_HALF', 'DC_REMOVE', 'ABS', 'BINNING', 'LOG_DB', 'CONCAT']
#    offset: 0
#    scale: 1
#    frame_skip: 1
#    log_mul: 20
#    log_base: 10
#    log_threshold: 1e-100
#    store_feat_ext_data: False
#    nn_for_feature_extraction: False

training:
    # enable/disable training
    enable: True #False
    # F28x generic timeseries model names: TimeSeries_Generic_1k_t, TimeSeries_Generic_4k_t, TimeSeries_Generic_6k_t, TimeSeries_Generic_13k_t
    model_name: 'TimeSeries_Generic_13k_t'
#    model_spec: ''
    batch_size: 256
    training_epochs: 20
    num_gpus: 0
#    learning_rate: 0.001

testing:
    enable: True

compilation:
    # enable/disable compilation
    enable: True #False
