common:
  task_type: generic_timeseries_classification
  target_device: MSPM0G5187
dataset:
  dataset_name: fall_detection_classification
  input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/01_04_00/datasets/fall_detection_classification.zip
data_processing_feature_extraction:
  feat_ext_transform: [ 'FFT_Q15', 'Q15_SCALE', 'Q15_MAG', 'DC_REMOVE', 'BIN_Q15', 'CONCAT']
  frame_size: 256
  feature_size_per_frame: 8
  num_frame_concat: 8
  variables: 3
  q15_scale_factor: 5
  normalize_bin: True
  stacking: '2D1'
training:
  model_name: CLS_6k_NPU
  batch_size: 256
  training_epochs: 50
  num_gpus: 0
testing: {}
compilation: {}
