DEVICE_RUN_INFO = {
    'ArcFault_model_1400_t': {
        'F280013': {'flash': 3576, 'inference_time_us': 2441, 'sram': 2280},
        'F280015': {'flash': 3576, 'inference_time_us': 2441, 'sram': 2280},
        'F28003': {'flash': 3576, 'inference_time_us': 2441, 'sram': 2280},
        'F28004': {'flash': 3576, 'inference_time_us': 2929, 'sram': 2280},
        'F2837': {'flash': 3576, 'inference_time_us': 2441, 'sram': 2280},
        'F28P55': {'flash': 3179, 'inference_time_us': 395, 'sram': 2370},
        'F28P65': {'flash': 3576, 'inference_time_us': 1464, 'sram': 2280},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'ArcFault_model_200_t': {
        'F280013': {'flash': 1619, 'inference_time_us': 460, 'sram': 1026},
        'F280015': {'flash': 1619, 'inference_time_us': 460, 'sram': 1026},
        'F28003': {'flash': 1619, 'inference_time_us': 460, 'sram': 1026},
        'F28004': {'flash': 1619, 'inference_time_us': 552, 'sram': 1026},
        'F2837': {'flash': 1619, 'inference_time_us': 460, 'sram': 1026},
        'F28P55': {'flash': 2181, 'inference_time_us': 178, 'sram': 858},
        'F28P65': {'flash': 1619, 'inference_time_us': 276, 'sram': 1026},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'ArcFault_model_300_t': {
        'F280013': {'flash': 1797, 'inference_time_us': 847, 'sram': 1538},
        'F280015': {'flash': 1797, 'inference_time_us': 847, 'sram': 1538},
        'F28003': {'flash': 1797, 'inference_time_us': 847, 'sram': 1538},
        'F28004': {'flash': 1797, 'inference_time_us': 1017, 'sram': 1538},
        'F2837': {'flash': 1797, 'inference_time_us': 847, 'sram': 1538},
        'F28P55': {'flash': 2285, 'inference_time_us': 234, 'sram': 1606},
        'F28P65': {'flash': 1797, 'inference_time_us': 508, 'sram': 1538},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'ArcFault_model_700_t': {
        'F280013': {'flash': 1866, 'inference_time_us': 982, 'sram': 1538},
        'F280015': {'flash': 1866, 'inference_time_us': 982, 'sram': 1538},
        'F28003': {'flash': 1866, 'inference_time_us': 982, 'sram': 1538},
        'F28004': {'flash': 1866, 'inference_time_us': 1179, 'sram': 1538},
        'F2837': {'flash': 1866, 'inference_time_us': 982, 'sram': 1538},
        'F28P55': {'flash': 2623, 'inference_time_us': 272, 'sram': 1606},
        'F28P65': {'flash': 1866, 'inference_time_us': 589, 'sram': 1538},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'MotorFault_model_1_t': {
        'F280013': {'flash': 1214, 'inference_time_us': 423, 'sram': 1016},
        'F280015': {'flash': 1214, 'inference_time_us': 423, 'sram': 1016},
        'F28003': {'flash': 1214, 'inference_time_us': 423, 'sram': 1016},
        'F28004': {'flash': 1214, 'inference_time_us': 508, 'sram': 1016},
        'F2837': {'flash': 1214, 'inference_time_us': 423, 'sram': 1016},
        'F28P55': {'flash': 1953, 'inference_time_us': 159, 'sram': 1112},
        'F28P65': {'flash': 1214, 'inference_time_us': 254, 'sram': 1016},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'MotorFault_model_2_t': {
        'F280013': {'flash': 5262, 'inference_time_us': 11465, 'sram': 10872},
        'F280015': {'flash': 5262, 'inference_time_us': 11465, 'sram': 10872},
        'F28003': {'flash': 5262, 'inference_time_us': 11465, 'sram': 10872},
        'F28004': {'flash': 5262, 'inference_time_us': 13758, 'sram': 10872},
        'F2837': {'flash': 5262, 'inference_time_us': 11465, 'sram': 10872},
        'F28P55': {'flash': 4377, 'inference_time_us': 1180, 'sram': 3198},
        'F28P65': {'flash': 5262, 'inference_time_us': 6879, 'sram': 10872},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'MotorFault_model_3_t': {
        'F280013': {'flash': 3069, 'inference_time_us': 627, 'sram': 656},
        'F280015': {'flash': 3069, 'inference_time_us': 627, 'sram': 656},
        'F28003': {'flash': 3069, 'inference_time_us': 627, 'sram': 656},
        'F28004': {'flash': 3069, 'inference_time_us': 752, 'sram': 656},
        'F2837': {'flash': 3069, 'inference_time_us': 627, 'sram': 656},
        'F28P55': {'flash': 2754, 'inference_time_us': 221, 'sram': 1116},
        'F28P65': {'flash': 3069, 'inference_time_us': 376, 'sram': 656},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'FanImbalance_model_1_t': {
        'F280013': {'flash': 1214, 'inference_time_us': 423, 'sram': 1016},
        'F280015': {'flash': 1214, 'inference_time_us': 423, 'sram': 1016},
        'F28003': {'flash': 1214, 'inference_time_us': 423, 'sram': 1016},
        'F28004': {'flash': 1214, 'inference_time_us': 508, 'sram': 1016},
        'F2837': {'flash': 1214, 'inference_time_us': 423, 'sram': 1016},
        'F28P55': {'flash': 1953, 'inference_time_us': 159, 'sram': 1112},
        'F28P65': {'flash': 1214, 'inference_time_us': 254, 'sram': 1016},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'FanImbalance_model_2_t': {
        'F280013': {'flash': 5262, 'inference_time_us': 11465, 'sram': 10872},
        'F280015': {'flash': 5262, 'inference_time_us': 11465, 'sram': 10872},
        'F28003': {'flash': 5262, 'inference_time_us': 11465, 'sram': 10872},
        'F28004': {'flash': 5262, 'inference_time_us': 13758, 'sram': 10872},
        'F2837': {'flash': 5262, 'inference_time_us': 11465, 'sram': 10872},
        'F28P55': {'flash': 4377, 'inference_time_us': 1180, 'sram': 3198},
        'F28P65': {'flash': 5262, 'inference_time_us': 6879, 'sram': 10872},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'FanImbalance_model_3_t': {
        'F280013': {'flash': 3069, 'inference_time_us': 627, 'sram': 656},
        'F280015': {'flash': 3069, 'inference_time_us': 627, 'sram': 656},
        'F28003': {'flash': 3069, 'inference_time_us': 627, 'sram': 656},
        'F28004': {'flash': 3069, 'inference_time_us': 752, 'sram': 656},
        'F2837': {'flash': 3069, 'inference_time_us': 627, 'sram': 656},
        'F28P55': {'flash': 2754, 'inference_time_us': 221, 'sram': 1116},
        'F28P65': {'flash': 3069, 'inference_time_us': 376, 'sram': 656},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'CLS_1k_NPU': {
        'F280013': {'flash': 3242, 'inference_time_us': 14463, 'sram': 12320},
        'F280015': {'flash': 3242, 'inference_time_us': 14463, 'sram': 12320},
        'F28003': {'flash': 3242, 'inference_time_us': 14463, 'sram': 12320},
        'F28004': {'flash': 3242, 'inference_time_us': 17356, 'sram': 12320},
        'F2837': {'flash': 3242, 'inference_time_us': 14463, 'sram': 12320},
        'F28P55': {'flash': 3467, 'inference_time_us': 1257, 'sram': 6250},
        'F28P65': {'flash': 3242, 'inference_time_us': 8678, 'sram': 12320},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'CLS_6k_NPU': {
        'F280013': {'flash': 11331, 'inference_time_us': 11091, 'sram': 3264},
        'F280015': {'flash': 11331, 'inference_time_us': 11091, 'sram': 3264},
        'F28003': {'flash': 11331, 'inference_time_us': 11091, 'sram': 3264},
        'F28004': {'flash': 11331, 'inference_time_us': 13310, 'sram': 3264},
        'F2837': {'flash': 11331, 'inference_time_us': 11091, 'sram': 3264},
        'F28P55': {'flash': 6709, 'inference_time_us': 2235, 'sram': 8364},
        'F28P65': {'flash': 11331, 'inference_time_us': 6655, 'sram': 3264},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'CLS_ResAdd_3k': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'CLS_ResCat_3k': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'NAS': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'FCST_13k': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'FCST_LSTM10': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'FCST_LSTM8': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'FCST_3k': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },

    # NPU-Optimized Forecasting Models
    'FCST_500_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'FCST_1k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'FCST_2k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'FCST_4k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'FCST_6k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'FCST_8k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'FCST_10k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'FCST_20k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'REGR_10k': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'REGR_1k': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'REGR_3k': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'REGR_13k': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'REGR_4k': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },

    # NPU-Optimized Regression Models
    'REGR_500_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'REGR_2k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'REGR_6k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'REGR_8k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'REGR_20k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'AD_17k': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'AD_16k': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'AD_4k': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'AD_1k': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'AD_Linear': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'Ondevice_Trainable_AD_Linear': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C34': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },

    # NPU-Optimized Anomaly Detection Models
    'AD_500_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'AD_2k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'AD_6k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'AD_8k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'AD_10k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'AD_20k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'PIRDetection_model_1_t': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },

    # Image classification models
    'Lenet5': {
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },

    # NPU-Optimized Generic Classification Models
    'CLS_100_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'CLS_500_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'CLS_2k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'CLS_4k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'CLS_8k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'CLS_13k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'CLS_20k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC1352': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    },
    'CLS_55k_NPU': {
        'F280013': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F280015': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28003': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28004': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F2837': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P55': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F28P65': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29H85': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P58': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'F29P32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'CC2755': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3507': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G3519': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM0G5187': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'MSPM33C32': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM13E2': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM263P': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'},
        'AM261': {'flash': 'TBD', 'inference_time_us': 'TBD', 'sram': 'TBD'}
    }
}