
common:
    target_module: 'timeseries'
    task_type: 'generic_timeseries_classification'
    target_device: 'F28P55'
    run_name: '{date-time}/{model_name}'
dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_name: gas_sensor
    input_data_path: examples/gas_sensor/gas_sensor_dataset.zip
    split_type: within_files

data_processing_feature_extraction: # One or more can be cascaded in the list
    data_proc_transforms: [SimpleWindow]
    # SimpleWindow
    frame_size: 192
    stride_size: 0.02
    variables: 10
    scale: 0.00390625 # 1/256

training:
    # enable/disable training
    enable: True #False
    model_name: 'TimeSeries_Generic_1k_t'
    num_gpus: 0  # 1
    epochs: 20
    output_dequantize: False # True

testing:
    enable: True

compilation:
    # enable/disable compilation
    enable: True #False