
common:
    target_module: 'timeseries'
    task_type: 'generic_timeseries_classification'
    target_device: 'F28P55'
    run_name: '{date-time}/{model_name}'

dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_name: electrical_fault
    input_data_path: 'examples/electrical_fault/electrical_fault_dataset.zip'

data_processing_feature_extraction:
    data_proc_transforms: [SimpleWindow]
    # SimpleWindow
    frame_size: 192
    stride_size: 0.01
    variables: 6

    feature_extraction_name: Custom_Default
    feat_ext_transform: []
   # FFT with Binning
#    feat_ext_transform: ['FFT_FE', 'FFT_POS_HALF', 'DC_REMOVE', 'ABS', 'BINNING', 'LOG_DB', 'CONCAT']
#    frame_size: 192
#    feature_size_per_frame: 48
#    num_frame_concat: 4

    # FFT without Binning
#    feat_ext_transform: ['FFT_FE', 'FFT_POS_HALF', 'DC_REMOVE', 'ABS', 'LOG_DB', 'CONCAT']
#    frame_size: 192
#    feature_size_per_frame: 96
#    num_frame_concat: 4

training:
    # enable/disable training
    enable: True #False
    model_name: 'Res_Cat_TimeSeries_Generic_3k_t'
    num_gpus: 0

testing:
    enable: True
    skip_train: False  # True

compilation:
    # enable/disable compilation
    enable: True #False