#################################################################################
# Copyright (c) 2023-2026, Texas Instruments
# All Rights Reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#################################################################################

"""
Constants used for model descriptions and device information.
This is a subset of constants from tinyml-modelmaker needed for model metadata.
"""

# Task types
TASK_TYPE_MOTOR_FAULT = 'motor_fault'
TASK_TYPE_ARC_FAULT = 'arc_fault'
TASK_TYPE_ECG_CLASSIFICATION = 'ecg_classification'
TASK_TYPE_BLOWER_IMBALANCE = 'blower_imbalance'
TASK_TYPE_PIR_DETECTION = 'pir_detection'
TASK_TYPE_GENERIC_TS_CLASSIFICATION = 'generic_timeseries_classification'
TASK_TYPE_GENERIC_TS_REGRESSION = 'generic_timeseries_regression'
TASK_TYPE_GENERIC_TS_ANOMALYDETECTION = 'generic_timeseries_anomalydetection'
TASK_TYPE_GENERIC_TS_FORECASTING = 'generic_timeseries_forecasting'

TASK_TYPES = [
    TASK_TYPE_ARC_FAULT,
    TASK_TYPE_MOTOR_FAULT,
    TASK_TYPE_ECG_CLASSIFICATION,
    TASK_TYPE_BLOWER_IMBALANCE,
    TASK_TYPE_GENERIC_TS_CLASSIFICATION,
    TASK_TYPE_GENERIC_TS_REGRESSION,
    TASK_TYPE_GENERIC_TS_ANOMALYDETECTION,
    TASK_TYPE_GENERIC_TS_FORECASTING,
    TASK_TYPE_PIR_DETECTION,
]

# Task categories
TASK_CATEGORY_TS_CLASSIFICATION = 'timeseries_classification'
TASK_CATEGORY_TS_REGRESSION = 'timeseries_regression'
TASK_CATEGORY_TS_ANOMALYDETECTION = 'timeseries_anomalydetection'
TASK_CATEGORY_TS_FORECASTING = 'timeseries_forecasting'

TASK_CATEGORIES = [
    TASK_CATEGORY_TS_CLASSIFICATION,
    TASK_CATEGORY_TS_REGRESSION,
    TASK_CATEGORY_TS_FORECASTING,
    TASK_TYPE_GENERIC_TS_ANOMALYDETECTION,
]

# Target devices
TARGET_DEVICE_AM263 = 'AM263'
TARGET_DEVICE_AM263P = 'AM263P'
TARGET_DEVICE_AM261 = 'AM261'
TARGET_DEVICE_F280013 = 'F280013'
TARGET_DEVICE_F280015 = 'F280015'
TARGET_DEVICE_F28003 = 'F28003'
TARGET_DEVICE_F28004 = 'F28004'
TARGET_DEVICE_F2837 = 'F2837'
TARGET_DEVICE_F28P55 = 'F28P55'
TARGET_DEVICE_F28P65 = 'F28P65'
TARGET_DEVICE_F29H85 = 'F29H85'
TARGET_DEVICE_F29P58 = 'F29P58'
TARGET_DEVICE_F29P32 = 'F29P32'
TARGET_DEVICE_MSPM0G3507 = 'MSPM0G3507'
TARGET_DEVICE_MSPM0G3519 = 'MSPM0G3519'
TARGET_DEVICE_MSPM0G5187 = 'MSPM0G5187'
TARGET_DEVICE_MSPM33C32 = 'MSPM33C32'
TARGET_DEVICE_MSPM33C34 = 'MSPM33C34'
TARGET_DEVICE_AM13E2 = 'AM13E2'
TARGET_DEVICE_CC2755 = 'CC2755'
TARGET_DEVICE_CC1352 = 'CC1352'
TARGET_DEVICE_CC1354 = 'CC1354'
TARGET_DEVICE_CC35X1 = 'CC35X1'

TARGET_DEVICES = [
    TARGET_DEVICE_F280013,
    TARGET_DEVICE_F280015,
    TARGET_DEVICE_F28003,
    TARGET_DEVICE_F28004,
    TARGET_DEVICE_F2837,
    TARGET_DEVICE_F28P55,
    TARGET_DEVICE_F28P65,
    TARGET_DEVICE_MSPM0G3507,
    TARGET_DEVICE_MSPM0G3519,
    TARGET_DEVICE_MSPM0G5187,
    TARGET_DEVICE_MSPM33C32,
    TARGET_DEVICE_F29H85,
    TARGET_DEVICE_CC2755,
    TARGET_DEVICE_CC1352,
    TARGET_DEVICE_CC1354,
    TARGET_DEVICE_CC35X1,
    TARGET_DEVICE_AM263,
    TARGET_DEVICE_AM263P,
    TARGET_DEVICE_AM261,
    TARGET_DEVICE_AM13E2,
]

TARGET_DEVICES_ADDITIONAL = [
    TARGET_DEVICE_MSPM33C34,
    TARGET_DEVICE_F29P58,
    TARGET_DEVICE_F29P32,
]

TARGET_DEVICES_ALL = TARGET_DEVICES + TARGET_DEVICES_ADDITIONAL

# Training devices
TRAINING_DEVICE_CPU = 'cpu'
TRAINING_DEVICE_CUDA = 'cuda'
TRAINING_DEVICE_MPS = 'mps'
TRAINING_DEVICE_GPU = TRAINING_DEVICE_CUDA

TRAINING_DEVICES = [
    TRAINING_DEVICE_CPU,
    TRAINING_DEVICE_CUDA,
    TRAINING_DEVICE_MPS,
]

# Default batch sizes per task type
TRAINING_BATCH_SIZE_DEFAULT = {
    TASK_TYPE_ARC_FAULT: 32,
    TASK_TYPE_MOTOR_FAULT: 256,
    TASK_TYPE_ECG_CLASSIFICATION: 12,
    TASK_TYPE_BLOWER_IMBALANCE: 256,
    TASK_TYPE_GENERIC_TS_CLASSIFICATION: 64,
    TASK_TYPE_GENERIC_TS_REGRESSION: 64,
    TASK_TYPE_GENERIC_TS_ANOMALYDETECTION: 64,
    TASK_TYPE_GENERIC_TS_FORECASTING: 64,
    TASK_TYPE_PIR_DETECTION: 64,
}
