
common:
    target_module: 'timeseries'
    task_type: 'generic_timeseries_classification'
    target_device: 'F28P55'
    run_name: '{date-time}/{model_name}'

dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_name: wisdm_example
    input_data_path: 'examples/branched_model_parameters/wisdm_dataset.zip'

data_processing: # One or more can be cascaded in the list
    # transforms: 'DownSample SimpleWindow'
    transforms: [SimpleWindow]
    # Downsample
    sampling_rate: 313000
    new_sr: 3130
    # SimpleWindow
    sequence_window: 128
    stride_size: 0.01
    variables: 3

feature_extraction:
   feature_extraction_name: Custom_Default
   transform: []
   store_feat_ext_data: False

training:
    # enable/disable training
    enable: True #False
    model_name: 'Res_TimeSeries_Generic_3k_t'
    model_config: 'examples/branched_model_parameters/residual_network_config.yaml'
    batch_size: 32
    training_epochs: 10
    num_gpus: 0

testing:
    enable: True
    skip_train: False  # True

compilation:
    # enable/disable compilation
    enable: True #False