common:
  task_type: generic_timeseries_classification
  target_device: MSPM0G5187

dataset:
  dataset_name: electrical_fault
  input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/01_04_00/datasets/electrical_fault_6class_dataset.zip

data_processing_feature_extraction:
  data_proc_transforms: ['SimpleWindow']
  frame_size: 128
  stride_size: 0.01
  variables: 3
  feature_extraction_name: Custom_Default
  feat_ext_transform: ['FFT_Q15', 'DC_REMOVE', 'Q15_MAG', 'BIN_Q15', 'LOG_DB', 'CONCAT']
  feature_size_per_frame: 32
  num_frame_concat: 8

training:
  model_name: ElectricalFault_model_40k_t
  training_epochs: 25
  num_gpus: 0

testing: {}

compilation: {}
