common:
    target_module: 'timeseries'
    task_type: 'motor_fault'
    target_device: 'MSPM0G5187'
    run_name: '{date-time}/{model_name}'

#### Original
dataset:
    # enable/disable dataset loading
    enable: True #False
    dataset_name: motor_fault_example_dsk

data_processing: # One or more can be cascaded in the list
    # transforms: 'DownSample SimpleWindow'
    transforms: []
    # Downsample
    sampling_rate: 313000
    new_sr: 3130
    # SimpleWindow
    sequence_window: 256
    stride_size: 0.01
    variables: 1

data_processing_feature_extraction:
   feature_extraction_name: MotorFault_128Input_RAW_128Feature_1Frame_3InputChannel_removeDC_2D1

training:
    model_name: 'CLS_1k_NPU'
    training_epochs: 20
    num_gpus: 0
    quantization_method: 'QAT'  # QAT/PTQ
    quantization_weight_bitwidth: 4
    quantization_activation_bitwidth: 8
    quantization: 2

testing: {}
compilation: {}